language: python
python:
  - 2.7
install: 
  - pip install . --use-mirrors
  - pip install nose --use-mirrors
  - pip install pep8 --use-mirrors
script: 
  - "pep8 --ignore=E501,E225,E128 google_spreadsheet"
  - nosetests 
